# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StepTechnicalTest' do
  pod 'RxSwift', '6.5.0'
  pod 'RxAlamofire', '6.1.1'
end

target 'LocalStepTechnicalTest' do
  pod 'RxSwift', '6.5.0'
  pod 'RxAlamofire', '6.1.1'
end

target 'StepTechnicalUnitTests' do
  pod 'RxAlamofire', '6.1.1'
  pod 'RxSwift', '6.5.0'
end

target 'StepTechnicalSnapshotTests' do
  pod 'RxAlamofire', '6.1.1'
  pod 'RxSwift', '6.5.0'
  pod 'SnapshotTesting', '1.9.0'
end
